version: "3.2"

services:
  PostgreSQL:
    container_name: pgsql-rmbl
    restart: always
    build: pgdb
    image: rmbl-pgdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rmbldb
    volumes:
      - pgdata:/var/lib/postgresql/data
  TestPostgreSQL:
    container_name: pgsql-rmbl-test
    restart: always
    build: pgdb
    image: rmbl-pgdb
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rmbltestdb
    # No Volume as no test data should be kept after

volumes:
  pgdata: